using System.Reflection;

namespace winpkg
{
internal static class Config
{
internal static readonly string version = Assembly.GetExecutingAssembly().GetName().Version.ToString().Substring(0,5);
internal static readonly string publisher =  "winpkg";
internal static readonly string link = "https://github.com/dmaccormac/winpkg";
internal static readonly string date = DateTime.Now.ToString("yyyyMMdd");



internal static readonly string help =
$"""
Package installer wrapper for Windows

winpkg [/I] [/B] [/BB] [/BC] [/X]  <SOURCE ...>

SOURCE   folder(s) containing application files

This program creates an installer and uninstaller package for any program files. 
It copies source files to the 'Apps' folder in the user's home directory. 
It adds the installation path to the user PATH variable.
It creates an uninstaller for the app in Windows Settings.
It adds shortcuts for new items to the Start Menu.

/B     Build installer (PowerShell default)
        winpkg /B C:\downloads\bar

/C     Build compact batch file installer

/I     Install the application
        winpkg /I C:\downloads\foo

/T     Build default batch file installer

/X     Executable installer

Version: {version}
Website: {link}
""";



internal static readonly string uninstall =
@"cmd.exe /q /c ""for /f ""skip=2 tokens=3*"" %a in ('reg query HKCU\Environment /v PATH')" +
@" do set p=""%a %b""" +
@" & call set p=%p:; =;%" + //trim possible trailing whitespace
@" & call setx PATH %p:destinationPath;=%" +
@" & reg delete ""HKCU\baseRegistryKey"" /f" +
@" & rd /q /s ""destinationPath""" +
@" & rd /q /s ""startMenuPath""""";



internal static readonly string batchFile = $@"@echo off
:: displayName installer auto-generated by winpkg.exe {DateTime.Now}

:: CONFIG VARS
set src=sourcePath
set app=displayName
set dst=destinationPath
set key=HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\%app%
set unx=cmd /q /c """"for /f """"skip=2 tokens=3*"""" %%a in ('reg query HKCU\Environment /v PATH') do set p=""""%%a %%b"""" ^& call set p=%%p:; =;%% ^& call setx PATH %%p:%dst%;=%% ^& reg delete """"%key%"""" /f ^& rd /q /s """"%dst%"""" ^& rd /q /s """"%APPDATA%\Microsoft\Windows\Start Menu\Programs\%app%""""
set ver=1.1.9(batch)

echo winpkg %ver%
echo Installing %src% ==^> %dst%

:: COPY FILES
xcopy ""%src%"" ""%dst%"" /E /I /H /Y /Q 1>nul

:: REGISTRY KEYS
reg add ""%key%"" /v ""DisplayName"" /t REG_SZ /d ""%app%"" /f 1>nul
reg add ""%key%"" /v ""UninstallString"" /t REG_SZ /d ""%unx%"" /f 1>nul
reg add ""%key%"" /v ""Publisher"" /t REG_SZ /d ""winpkg"" /f 1>nul
reg add ""%key%"" /v ""HelpLink"" /t REG_SZ /d ""https://github.com/dmaccormac/winpkg"" /f 1>nul

:: SET PATH
for /f ""skip=2 tokens=3*"" %%a in ('reg query HKCU\Environment /v PATH') do (set p=""%%~a %%~b"")
set p=%p:""=%
set p=%p:; =;%
setx PATH ""%p%%dst%;"" 1>nul

:: START MENU
mkdir ""%APPDATA%\Microsoft\Windows\Start Menu\Programs\%app%"" 2>nul

for /f ""delims="" %%a in ('dir /S /B ""%dst%\*.exe""') do (
echo Set objShell = CreateObject^(""WScript.Shell""^) > winpkg.vbs
echo Set objShortcut = objShell.CreateShortcut^(""%APPDATA%\Microsoft\Windows\Start Menu\Programs\%app%\%%~na.lnk""^) >> winpkg.vbs
echo objShortcut.TargetPath = ""%%a"" >> winpkg.vbs
echo objShortcut.IconLocation = ""%%a%"" >> winpkg.vbs
echo objShortcut.Save >> winpkg.vbs
cscript //nologo //b winpkg.vbs
del /q winpkg.vbs
)
";



internal static readonly string compactBatchFile = @"@echo off
set o=%tmp%\w.vbs
set s=sourcePath
set a=displayName
set m=%APPDATA%\Microsoft\Windows\Start Menu\Programs\%a%
set d=%USERPROFILE%\Apps\%a%
set k=HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\%a%
set u=cmd /q /c """"for /f """"skip=2 tokens=3*"""" %%x in ('reg query HKCU\Environment /v PATH') do set p=""""%%x %%y"""" ^& call set p=%%p:; =;%% ^& call setx PATH %%p:%d%;=%% ^& reg delete """"%k%"""" /f ^& rd /q /s """"%d%"""" """"%m%""""""""
xcopy ""%s%"" ""%d%"" /E /I /H /Y /Q
reg add ""%k%"" /v ""DisplayName"" /d ""%a%"" /f
reg add ""%k%"" /v ""UninstallString"" /d ""%u%"" /f
for /f ""skip=2 tokens=3*"" %%x in ('reg query HKCU\Environment /v PATH') do (set p=""%%~x %%~y"")
set p=%p:""=%
set p=%p:; =;%
setx PATH ""%p%%d%;""
mkdir ""%m%""
for /f ""delims="" %%x in ('dir /s /b ""%d%\*.exe""') do (echo Set objShell=CreateObject^(""WScript.Shell""^):Set objShortcut=objShell.CreateShortcut^(""%m%\%%~nx.lnk""^):objShortcut.TargetPath=""%%x"":objShortcut.Save > %o% & cscript %o% & del /q %o%)";



}
}